#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &
mpd &
picom &
dunst &
xscreensaver -no-splash &
xset s 300 300 & # time for suspend screen
xset dpms 300 300 300 &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
remaps &
xinput set-prop "pointer:Logitech MX Master 3" "libinput Accel Profile Enabled" 0 1 &
unclutter &
dwmblocks &

# Laptop
mihostname=$(cat /proc/sys/kernel/hostname)
if [ "$mihostname" = 'archlaptop' ] || [ "$mihostname" = 'thinkpad' ]; then
  laptop-config
fi
