#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg & # set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
mpd &
remaps &
picom &
dunst &
xscreensaver -no-splash &
xinput set-prop 12 "libinput Accel Profile Enabled" 0 1 & # logitech, disabled mouse acceleration
xset s 300 300 & # time for suspend screen
xset dpms 300 300 300 & # time for suspend screen
unclutter & # Remove mouse when idle
dwmblocks &

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

mihostname=$(cat /proc/sys/kernel/hostname)
if [ "$mihostname" = 'archlaptop' ];
then
  xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources_laptop
  xbacklight -set 5 &
  dropbox &
fi
