#!/bin/sh

# Use neovim for vim if present.
# [ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su ; do
	alias $command="sudo $command"
done; unset command

# Neovim
alias n=nvim

# Git
alias \
  g="git" \
  gps='g add . && g commit -m "Wip" && g push'

# With this one we can use our alias with sudo
alias sudo="sudo "

# Colorize commands when possible.
alias \
	ls="exa -lhg" \
	l="ls -a" \
	diff="diff --color=auto" \
  cat="bat"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \

alias -s html="$BROWSER"
alias -s ts=nvim
alias -s js=nvim
alias -s py=nvim
alias pip=pip3

# Shortcuts
alias \
..="cd .. && l" \
...="cd ../.. && l" \
....="cd ../../.. && l" \
gh="cd ~ && l" \
gd="cd /home/juan/Downloads && l" \
go="cd /home/juan/Documents && l" \
gp="cd /home/juan/Pictures && l" \
gv="cd ~/Videos && l" \
gm="cd ~/Music && l" \
gc="cd ~/code && l" \
gw="cd ~/code/workspace && l" \
g.="cd ~/dotfiles && l" \
gC="cd ~/.config && l" \
gz="cd ~/.config/zsh && l" \
gn="cd ~/.config/nvim && l" \
gf="cd ~/.config/lf && l" \
gs="cd ~/.config/shell && l" \
gb="cd "$HOME/.local/bin" && l" \
glsr="cd "$HOME/.local/src" && l" \
glsh="cd "$HOME/.local/share" && l" \
g/="cd / && l" \
gE="cd /etc && l" \
gB="cd /boot && l" \
gM="cd /mnt && l" \
gU="cd /usr && l" \
gO="cd /opt && l" \
gL="cd /usr/lib && l" \
gB="cd /usr/bin && l" \
gV="cd /var && l" \
gta="$EDITOR "$HOME/.config/shell/aliasrc"" \
gts="$EDITOR "$HOME/.config/shell/shortcutrc"" \
gtp="$EDITOR "$HOME/.config/shell/profile"" \
gtn="$EDITOR "$HOME/.config/nvim/init.lua"" \
gtz="$EDITOR "$HOME/.config/zsh/.zshrc"" \
gtfr="$EDITOR "$HOME/.config/lf/lfrc"" \
gtfs="$EDITOR "$HOME/.config/lf/shortcutrc"" \
