require("plugins/nvim-tree")
require("plugins/which-key")
require("plugins/lualine")
require("plugins/nvim-lsp")
require("plugins/treesitter")
require("plugins/format")
require("plugins/lsp")
require("plugins/cmp")
